### ISSUE TITLE
Compatible USB2EPP adapter

### ISSUE THREAD

**Issue by s-weigand** [shugaa/estrella#3]
First of all thanks for for this project.
We want to transition from using a PC with LabView to control our `StellarNet EPP2000` with a RaspberryPi for students to do remote experiments.
Only Problem is that our `USB2EPP` adapter from StellarNet has some hardware problems and StellarNet doesn't sell them anymore.
So I was wandering if any of you (@shugaa @kstenio) still uses the original `USB2EPP` adapter or if you found a compatible adapter.

Another option for us would be to use [this hat for the RaspberryPi](https://github.com/worlickwerx/pi-parport) and directly talk via `IEEE-1284` but I can't find the spec files for the protocol. 
How did you manage to write the usb driver? 
Did you reverse engineer it?
Or do you know where to get the protocol specs?

Thanks a lot in advance.

**Comment by kstenio** [comment]
Hello @s-weigand.

Well, I don't know about @shugaa, but I believe he doesn't have access to these spectrometers anymore. For me, I have an old RPi-2 controlling one EPP2000, and I use it with the adapter provided by StellarNet (without problems so far).

About reverse engineering and all, I'm afraid I can't help since I developed just the Python bindings.

**Comment by s-weigand** [comment]
Sorry for the late reply and thank you for detailed answer.
